### ISSUE TITLE
[Error] Failed to process update information

### ISSUE THREAD

**Issue by DatsiK96** [baileyholl/Ars-Nouveau#116]
Just an update checker fail. Just an FYI
```
[26Dec2020 12:04:39.998] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [ars_nouveau] Starting version check at http://myurl.me/
[26Dec2020 12:04:40.201] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
java.io.IOException: Server returned HTTP response code: 403 for URL: http://myurl.me/
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945) ~[?:1.8.0_271]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_271]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:171) ~[forge:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_271]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://myurl.me/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_271]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_271]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_271]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:155) ~[forge:?]
	... 3 more

```

**Comment by baileyholl** [comment]
Resolved in next update.

**Comment by DatsiK96** [comment]
Awesome, thanks!
