### ISSUE TITLE
Worn Notebook returns error for page 3

### ISSUE THREAD

**Issue by Mystara0001** [baileyholl/Ars-Nouveau#1168]
When trying to read the worn notebook, I received the following error:

![Minecraft Forge_ 1 20 1 - Singleplayer_2023-11-23_10-16-07](https://github.com/baileyholl/Ars-Nouveau/assets/6118189/0bd97d80-125c-4f70-8cf3-4314a5bb7dc4)

The crash log is pasted below

```
[23Nov2023 10:12:12.651] [Render thread/ERROR] [patchouli/]: Error loading and compiling book ars_nouveau:worn_notebook, using empty contents
java.lang.RuntimeException: Error building entry ars_nouveau:familiars/summoning_familiars of book ars_nouveau:worn_notebook
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:97) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:93) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.book.BookContentsBuilder.loadAndBuildFor(BookContentsBuilder.java:73) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:194) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:99) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:64) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$bpj000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1316) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23712!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.6.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.6.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Error while building entry ars_nouveau:familiars/summoning_familiars page 3 of book ars_nouveau:worn_notebook
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:242) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:95) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	... 35 more
Caused by: java.lang.IllegalArgumentException: Could not find entry ars_nouveau:rituals/binding
	at vazkii.patchouli.client.book.page.PageRelations.build(PageRelations.java:36) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:238) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:95) ~[Patchouli-1.20.1-83-FORGE.jar%23648!/:1.20.1-83-FORGE]
	... 35 more
```

**Comment by connorglasgow** [comment]
I was also having this error in this mod and others. It is a patchouli issue, revert to version 1.20.1-81 and the error will be gone.
