### ISSUE TITLE
Issue with missing Recipe?

### ISSUE THREAD

**Issue by ModernGamingWorld** [baileyholl/Ars-Nouveau#127]
[02.01 23:18:37] [Server] [Worker-Main-12/ERROR] [minecraft/LootTableManager]: Couldn't parse loot table ars_nouveau:blocks/archwood_wall_sign
[02.01 23:18:37] [Server] com.google.gson.JsonSyntaxExceptionExpected name to be an item, was unknown string 'ars_nouveau:archwood_wall_sign'
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_219793_a(SourceFile:127) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188172_b(SourceFile:127) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188180_i(SourceFile:135) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:55) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:40) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:151) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:129) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:86) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:74) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:448) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:183) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:180) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:245) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:242) ~[?:?] {re:classloading}
[02.01 23:18:37] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.16.4-20201102.104115-extra.jar:?] {re:mixin}
[02.01 23:18:37] [Server] 	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:853) ~[forge:?] {re:mixin,re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[02.01 23:18:37] [Server] 	at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[02.01 23:18:37] [Server] 	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A}
[02.01 23:18:37] [Server] 	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {}
[02.01 23:18:37] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}

**Comment by Yourname942** [comment]
I am getting this error as well:
latest log https://gist.github.com/Yourname942/c46928f9b3da424ccc07ea86de848537

Minecraft 1.16.4
Forge 35.1.29
Ars Nouveau 1.10.6
