### ISSUE TITLE
[Crash] Forge Dedicate Server v51.0.33 do not start

### ISSUE THREAD

**Issue by Zilgyd** [baileyholl/Ars-Nouveau#1414]
Hi, minecraft server 1.21 with forge v51.0.33 do not start here is crash report, is the only mod ars-noveau for 1.21 installed, I hope be useful, greetings =):

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-09-14 17:17:19
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:49) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:127) ~[forge-1.21-51.0.33-server.jar:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
        at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) [forge-1.21-51.0.33-shim.jar:2.1.3] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:52) ~[forge-1.21-51.0.33-universal.jar!/:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
        Mod File: NO FILE INFO
        Failure message: Invalid mod file found /data/mods/ars_nouveau-1.21.0-5.1.0-all.jar
        Mod Version: NO MOD INFO AVAILABLE
        Mod Issue URL: NOT PROVIDED
        Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:52) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:50) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:127) ~[forge-1.21-51.0.33-server.jar:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
        at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) [forge-1.21-51.0.33-shim.jar:2.1.3] {}

-- System Details --
Details:
        Minecraft Version: 1.21
        Minecraft Version ID: 1.21
        Operating System: Linux (amd64) version 6.8.0-41-generic
        Java Version: 21.0.4, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 821698016 bytes (783 MiB) / 1073741824 bytes (1024 MiB) up to 5242880000 bytes (5000 MiB)
        CPUs: 4
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 7 5800X 8-Core Processor
        Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
        Microarchitecture: Zen 3
        Frequency (GHz): -0.00
        Number of physical packages: 4
        Number of physical CPUs: 4
        Number of logical CPUs: 4
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MiB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MiB): 9307.67
        Virtual memory used (MiB): 1678.46
        Swap memory total (MiB): 0.00
        Swap memory used (MiB): 0.00
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 174203.84, total: 177476.73
        Space in storage for workdir (MiB): available: 174203.84, total: 177476.73
        JVM Flags: 2 total; -Xmx5000M -Xms1024M
        ModLauncher: 10.2.1
        ModLauncher launch target: forge_server
        ModLauncher naming: mcp
        ModLauncher services: 
                / slf4jfixer PLUGINSERVICE 
                / runtimedistcleaner PLUGINSERVICE 
                / runtime_enum_extender PLUGINSERVICE 
                / object_holder_definalize PLUGINSERVICE 
                / capability_token_subclass PLUGINSERVICE 
                / accesstransformer PLUGINSERVICE 
                / eventbus PLUGINSERVICE 
                / mixin PLUGINSERVICE 
                / fml TRANSFORMATIONSERVICE 
                / mixin TRANSFORMATIONSERVICE 
        FML Language Providers: 
                minecraft@1.0
                lowcodefml@51
                javafml@51.0.33
        Mod List: 
                forge-1.21-51.0.33-server.jar                     |Minecraft                     |minecraft                     |1.21                |NONE      |Manifest: NOSIGNATURE
                forge-1.21-51.0.33-universal.jar                  |Forge                         |forge                         |51.0.33             |NONE      |Manifest: NOSIGNATURE[17:17:19] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Invalid mod file found /data/mods/ars_nouveau-1.21.0-5.1.0-all.jar
]
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.21-51.0.33/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:151) ~[fmlcore-1.21-51.0.33.jar:1.0] {}
        at TRANSFORMER/forge@51.0.33/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.21-51.0.33-universal.jar:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:127) ~[forge-1.21-51.0.33-server.jar:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.21-51.0.33.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
        at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) [forge-1.21-51.0.33-shim.jar:2.1.3] {}
2024-09-14T17:17:20.089Z        INFO    mc-server-runner        Done

**Comment by baileyholl** [comment]
I would need the full server log if possible.
