### ISSUE TITLE
Potion Melder with high-powered potions crashes client

### ISSUE THREAD

**Issue by welch3694** [baileyholl/Ars-Nouveau#1526]
Pack: ATM10, v1.22
Ars Nouveau version: ars_nouveau-1.21.1-5.2.6-all

I decided to try using the potion melder to combine two potions that were super high-powered, each had a potency over 25. (Via other mod interactions you can empower potions arbitrarily higher than 10+, etc -- the potions were created using EvilCraft's Purifier combined with Ars' Potion Flask of Amplify & Extend Time, and showed up as "Mixed Potion" in the UI -- idk if that is relevant, but putting everything I can think of here.)

Inputting the requisite 3 doses of each potion into the two input potion jars and linking them to the potion melder worked fine, but the instant I selected the output potion jar my client crashed, and continues to crash every time I enter the server. 

Interestingly, or perhaps not, it does not crash the server, but it crashed my client. -- Crash report attached.

[crash-2024-11-25_12.38.28-client.txt](https://github.com/user-attachments/files/17906946/crash-2024-11-25_12.38.28-client.txt)

Expectation: Either a successfully melded potion of arbitrary potency, OR it simply does not attempt to meld them, if it can't produce an output without erroring.

**Comment by welch3694** [comment]
First few lines of the stack trace:

`java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143) ~[?:?] {re:mixin}
	at TRANSFORMER/ars_nouveau@5.2.6/com.hollingsworth.arsnouveau.common.util.PotionUtil.merge(PotionUtil.java:76) ~[ars_nouveau-1.21.1-5.2.6-all.jar%23600!/:5.2.6] {re:classloading}
	at TRANSFORMER/ars_nouveau@5.2.6/com.hollingsworth.arsnouveau.common.block.tile.PotionMelderTile.getCombinedResult(PotionMelderTile.java:171) ~[ars_nouveau-1.21.1-5.2.6-all.jar%23600!/:5.2.6] {re:classloading}
	at TRANSFORMER/ars_nouveau@5.2.6/com.hollingsworth.arsnouveau.common.block.tile.PotionMelderTile.getTooltip(PotionMelderTile.java:314) ~[ars_nouveau-1.21.1-5.2.6-all.jar%23600!/:5.2.6] {re:classloading}
	at TRANSFORMER/ars_nouveau@5.2.6/com.hollingsworth.arsnouveau.client.gui.GuiEntityInfoHUD.renderOverlay(GuiEntityInfoHUD.java:56) ~[ars_nouveau-1.21.1-5.2.6-all.jar%23600!/:5.2.6] {re:classloading}
	at TRANSFORMER/neoforge@21.1.79/net.neoforged.neoforge.client.gui.GuiLayerManager.renderInner(GuiLayerManager.java:69) ~[neoforge-21.1.79-universal.jar%23563!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.79/net.neoforged.neoforge.client.gui.GuiLayerManager.render(GuiLayerManager.java:59) ~[neoforge-21.1.79-universal.jar%23563!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.Gui.render$mixinextras$wrapped$108(Gui.java:234) ~[client-1.21.1-20240808.144430-srg.jar%23562!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.Gui.mixinextras$bridge$render$mixinextras$wrapped$108$109(Gui.java) ~[client-1.21.1-20240808.144430-srg.jar%23562!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.Gui.wrapMethod$zhj000$iris$handleHudHidingScreens(Gui.java:1520) ~[client-1.21.1-20240808.144430-srg.jar%23562!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.Gui.render(Gui.java) ~[client-1.21.1-20240808.144430-srg.jar%23562!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}`
