### ISSUE TITLE
PickupNotifier Mod incompatible, causing crash and/or rune error - 1.21.1

### ISSUE THREAD

**Issue by Temil2006** [baileyholl/Ars-Nouveau#1531]
When you have PickupNotifier mod installed, any Pickup spells on turrets or runes fail.
- on Rune, the rune gets destroyed, and says it had an error
- on a Turret, the server kicks out all clients until the pickup action can't be completed any more. Items are picked up, but they aren't placed into box while this turret is running.

below is the log from the server of the error. Parsed and to determine it was the PickupNotifier mod.. removed that from server and client, and pickup action on turret and rune now works.

<
breakdown this error log.

[02Dec2024 00:37:15.095] [Server thread/ERROR] [net.neoforged.bus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.minecraft.network.Connection.channel()" is null
	Index: 8
	Listeners:
		0: fuzs.pickupnotifier.neoforge.PickUpNotifierNeoForge$$Lambda/0x000001ed46f86200@2dc5f05
		1: net.neoforged.bus.EventListenerFactory$event/0x000001ed4783cc00@711d2235
		2: net.p3pp3rf1y.sophisticatedbackpacks.common.CommonEventHandler$$Lambda/0x000001ed47ff7948@1be5738c
		3: net.neoforged.bus.EventListenerFactory$giveStoneToBlacksmith/0x000001ed481bc800@20400ff9
		4: net.neoforged.bus.EventListenerFactory$entityPickup/0x000001ed48943000@30bf538f
		5: net.neoforged.bus.EventListenerFactory$onItemPickupPre/0x000001ed49618800@383e9162
		6: net.neoforged.bus.EventListenerFactory$onPickup/0x000001ed496a9800@20aa10da
		7: net.neoforged.bus.EventListenerFactory$on/0x000001ed49f8d000@35fcf1
		8: fuzs.pickupnotifier.neoforge.PickUpNotifierNeoForge$$Lambda/0x000001ed46f872f8@3e584c8d
		9: net.neoforged.bus.EventListenerFactory$itemPickupEvent/0x000001ed487f2400@4a5cf453
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.minecraft.network.Connection.channel()" is null
	at TRANSFORMER/neoforge@21.1.80/net.neoforged.neoforge.network.registration.ChannelAttributes.getPayloadSetup(ChannelAttributes.java:52)
	at TRANSFORMER/neoforge@21.1.80/net.neoforged.neoforge.network.registration.NetworkRegistry.hasChannel(NetworkRegistry.java:598)
	at TRANSFORMER/neoforge@21.1.80/net.neoforged.neoforge.common.extensions.ICommonPacketListener.hasChannel(ICommonPacketListener.java:59)
	at TRANSFORMER/neoforge@21.1.80/net.neoforged.neoforge.common.extensions.ICommonPacketListener.hasChannel(ICommonPacketListener.java:66)
	at TRANSFORMER/puzzleslib@21.1.22/fuzs.puzzleslib.neoforge.impl.core.NeoForgeAbstractions.hasChannel(NeoForgeAbstractions.java:46)
	at TRANSFORMER/puzzleslib@21.1.22/fuzs.puzzleslib.api.network.v3.PlayerSet.lambda$ofPlayer$1(PlayerSet.java:65)
	at TRANSFORMER/puzzleslib@21.1.22/fuzs.puzzleslib.impl.network.NetworkHandlerRegistryImpl.sendMessage(NetworkHandlerRegistryImpl.java:51)
	at TRANSFORMER/puzzleslib@21.1.22/fuzs.puzzleslib.api.network.v3.NetworkHandler.sendTo(NetworkHandler.java:108)
	at TRANSFORMER/pickupnotifier@21.1.0/fuzs.pickupnotifier.neoforge.handler.NeoForgeItemPickupHandler.onEntityItemPickup$2(NeoForgeItemPickupHandler.java:59)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.common.spell.effect.EffectPickup.onResolve(EffectPickup.java:46)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.api.spell.SpellResolver.resume(SpellResolver.java:189)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.api.spell.SpellResolver.resolveAllEffects(SpellResolver.java:158)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.api.spell.SpellResolver.onResolveEffect(SpellResolver.java:150)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.common.spell.method.MethodTouch.onCastOnEntity(MethodTouch.java:61)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.api.spell.SpellResolver.onCastOnEntity(SpellResolver.java:135)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.common.block.tile.RuneTile.castSpell(RuneTile.java:77)
	at TRANSFORMER/ars_nouveau@5.3.3/com.hollingsworth.arsnouveau.common.block.RuneBlock.tick(RuneBlock.java:109)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:730)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:762)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:367)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:317)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1570)
>

**Comment by baileyholl** [comment]
this should be reported to them, ars only fires the item pickup event for other mods to listen to. Looks like they aren't checking the proper side.
