### ISSUE TITLE
Crash when crops grow.

### ISSUE THREAD

**Issue by FierceManul** [baileyholl/Ars-Nouveau#160]
Not 100% crash, but high probability.

[271月2021 15:35:11.709] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@10b7dbfb cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		2: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@4836fbe1 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		3: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@4d9294c4 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		4: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@2dd56639 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		5: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@36cb8afa cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		6: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@495d9631 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		7: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@10301f6a cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		8: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@bfaf707 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		9: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@6e9229ca cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		10: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@3e86783d cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		11: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@1a784826 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		12: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@46e6d6a1 cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
		13: ASM: com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile@39457bce cropGrow(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Post;)V
java.lang.NullPointerException
	at com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile.cropGrow(ManaCondenserTile.java:65)
	at net.minecraftforge.eventbus.ASMEventHandler_743_ManaCondenserTile_cropGrow_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPost(ForgeHooksMixin.java:1014)
	at net.minecraft.block.CropsBlock.func_225542_b_(CropsBlockMixin.java:71)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock_AbstractBlockStateMixin.java:622)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorldMixin.java:508)
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProviderMixin.java:362)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProviderMixin.java:346)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProviderMixin.java:321)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:333)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)
[271月2021 15:35:11.715] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 58244f4e-36d2-485d-b600-ca19b7d24d52
[271月2021 15:35:11.727] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile.cropGrow(ManaCondenserTile.java:65) ~[?:1.11.2]
	at net.minecraftforge.eventbus.ASMEventHandler_743_ManaCondenserTile_cropGrow_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPost(ForgeHooksMixin.java:1014) ~[?:?]
	at net.minecraft.block.CropsBlock.func_225542_b_(CropsBlockMixin.java:71) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock_AbstractBlockStateMixin.java:622) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorldMixin.java:508) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProviderMixin.java:362) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProviderMixin.java:346) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProviderMixin.java:321) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850) ~[?:?]
	... 5 more
[271月2021 15:35:11.728] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at com.hollingsworth.arsnouveau.common.block.tile.ManaCondenserTile.cropGrow(ManaCondenserTile.java:65) ~[?:1.11.2]
	at net.minecraftforge.eventbus.ASMEventHandler_743_ManaCondenserTile_cropGrow_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPost(ForgeHooksMixin.java:1014) ~[?:?]
	at net.minecraft.block.CropsBlock.func_225542_b_(CropsBlockMixin.java:71) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock_AbstractBlockStateMixin.java:622) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorldMixin.java:508) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProviderMixin.java:362) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProviderMixin.java:346) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProviderMixin.java:321) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1895) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

[latest (2).log](https://github.com/baileyholl/Ars-Nouveau/files/5884877/latest.2.log)

**Comment by baileyholl** [comment]
What type of crops were you growing? Anything modded?

**Comment by FierceManul** [comment]
wheat and beetroot, other not test.

**Comment by baileyholl** [comment]
This cannot be reproduced, another mod or a plugin is firing a bad growth event.
