### ISSUE TITLE
Worn Notebook Error in Chinese Locale

### ISSUE THREAD

**Issue by DotIN13** [baileyholl/Ars-Nouveau#175]
Minecraft: 1.16.5
Forge: 36.0.14
Patchouli: 1.16.4-48
Ars Nouveau: 1.11.4
Mods: only ars nouveau.
Screenshot:
https://imgur.com/py7ULH0

log:
```shell
[05二月2021 19:55:45.803] [Render thread/WARN] [patchouli/]: Failed to load ars_nouveau:patchouli_books/worn_notebook/zh_cn/categories/spells_3.json. Switching to fallback.
[05二月2021 19:55:45.804] [Render thread/WARN] [patchouli/]: Failed to load ars_nouveau:patchouli_books/worn_notebook/zh_cn/categories/spells_2.json. Switching to fallback.
[05二月2021 19:55:45.806] [Render thread/WARN] [patchouli/]: Failed to load ars_nouveau:patchouli_books/worn_notebook/zh_cn/categories/spells_1.json. Switching to fallback.
[05二月2021 19:55:45.809] [Render thread/WARN] [patchouli/]: Failed to load ars_nouveau:patchouli_books/worn_notebook/zh_cn/categories/release_notes.json. Switching to fallback.
[05二月2021 19:55:45.813] [Render thread/WARN] [patchouli/]: Failed to load ars_nouveau:patchouli_books/worn_notebook/zh_cn/entries/spells/wither.json. Switching to fallback.
[05二月2021 19:55:45.815] [Render thread/ERROR] [patchouli/]: Error while loading contents for book ars_nouveau:worn_notebook
java.lang.RuntimeException: Entry in file ars_nouveau:patchouli_books/worn_notebook/en_us/entries/spells/touch.json does not have a valid category.
	at vazkii.patchouli.client.book.BookContents.loadEntry(BookContents.java:201) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$1(BookContents.java:121) ~[patchouli:1.16.4-48]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_275]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:125) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) ~[patchouli:1.16.4-48]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_275]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:104) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) ~[patchouli:1.16.4-48]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$zen000$patchouli_onSync(SourceFile:518) ~[?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.14.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Comment by baileyholl** [comment]
Hello,
The chinese locale is very very outdated at the moment, and is unfortunately going to be broken until another PR is made to bring it up to date. Apologies for that.

For now, if at all possible, I would use the English or zh_tw localizations.

**Comment by DotIN13** [comment]
Thanks so much for looking into that! Will use zh_tw until it's fixed.
