### ISSUE TITLE
Worn Notebook Error

### ISSUE THREAD

**Issue by NerdicusRex** [baileyholl/Ars-Nouveau#178]
[11Feb2021 10:33:46.349] [Render thread/ERROR] [patchouli/]: Error while loading contents for book ars_nouveau:worn_notebook
java.lang.RuntimeException: Error building entry ars_nouveau:apparatus/carbuncle_charm
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[patchouli:1.16.4-48]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) ~[patchouli:1.16.4-48]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:104) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) ~[patchouli:1.16.4-48]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$zkg000$patchouli_onSync(SourceFile:518) ~[?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.10-launcher.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry ars_nouveau:apparatus/carbuncle_charm page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more
Caused by: java.lang.RuntimeException: Error setting up template processor
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more
Caused by: java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_251]
	at com.hollingsworth.arsnouveau.client.patchouli.ApparatusProcessor.setup(ApparatusProcessor.java:22) ~[ars_nouveau:1.11.3]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:92) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more
[11Feb2021 10:33:46.403] [Render thread/ERROR] [patchouli/]: Error while loading contents for book tomeofblood:bloody_notes
java.lang.RuntimeException: Error building entry ars_nouveau:apparatus/carbuncle_charm
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[patchouli:1.16.4-48]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.common.book.Book.reloadExtensionContents(Book.java:211) ~[patchouli:1.16.4-48]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) ~[patchouli:1.16.4-48]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$zkg000$patchouli_onSync(SourceFile:518) ~[?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.10-launcher.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry ars_nouveau:apparatus/carbuncle_charm page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more
Caused by: java.lang.RuntimeException: Error setting up template processor
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more
Caused by: java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_251]
	at com.hollingsworth.arsnouveau.client.patchouli.ApparatusProcessor.setup(ApparatusProcessor.java:22) ~[ars_nouveau:1.11.3]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:92) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[patchouli:1.16.4-48]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48]
	... 39 more

**Comment by baileyholl** [comment]
What pack, version, and lang are you running?

**Comment by NerdicusRex** [comment]
its Enigmatica 6 0.3.13, English

**Comment by baileyholl** [comment]
Is the entire book blank for you? That is likely an error with the Kube.js scripts in the pack not downloading correctly. I would ask the Enigmatica discord.

**Comment by NerdicusRex** [comment]
Table of contents and chapters are loading but when you go to them its blank with just a cube on the pages

**Comment by NerdicusRex** [comment]
We good thanks for your help!
