### ISSUE TITLE
Worn note note loading  contents

### ISSUE THREAD

**Issue by Deathrex007** [baileyholl/Ars-Nouveau#218]
I just found this issue recently, the worn notebook stopped loading the contents on its pages. I think someone has a similar issue.

here's what I got from the log.

[16Apr2021 01:27:21.050] [Render thread/ERROR] [patchouli/]: Error while loading contents for book ars_nouveau:worn_notebook
java.lang.RuntimeException: Error building entry ars_nouveau:spells/launch
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookContents$$Lambda$36220/1428908616.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_51]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) [?:1.16.4-50]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) [?:1.16.4-50]
	at vazkii.patchouli.common.book.BookRegistry$$Lambda$36208/149985992.accept(Unknown Source) [?:1.16.4-50]
	at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_51]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) [?:1.16.4-50]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) [?:1.16.4-50]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) [?:1.16.4-50]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$bjh000$patchouli_onSync(SourceFile:518) [?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$35159/1266624470.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/1801330629.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry ars_nouveau:spells/launch page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-50]
	... 34 more
Caused by: java.lang.RuntimeException: Error setting up template processor
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-50]
	... 34 more
Caused by: java.lang.IllegalArgumentException
	at com.hollingsworth.arsnouveau.client.patchouli.GlyphPressProcessor$$Lambda$36272/292071012.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_51]
	at com.hollingsworth.arsnouveau.client.patchouli.GlyphPressProcessor.setup(GlyphPressProcessor.java:20) ~[?:1.13.1]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:92) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:23) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16.4-50]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-50]
	... 34 more

**Comment by VT-14** [comment]
I believe I encountered a similar issue when I made recipe processors for the Blood Magic Patchouli Guidebook.

[Someone brought this up on Reddit](https://www.reddit.com/r/feedthebeast/comments/mw5ngk/not_sure_what_to_do_about_this_also_most_of_the/) and I asked if the Launch Glyph had a recipe in JEI.  They said it did not.

The issue I had was that the processors I wrote at the time didn't properly handle a missing/invalid recipe.  A missing recipe caused the processor's setup code to error, which caused Patchouli to stop trying to load any more of the book.  About half the book ended up being blank.

I suspect that the current [GlyphPressProcessor](https://github.com/baileyholl/Ars-Nouveau/blob/1.16.2/src/main/java/com/hollingsworth/arsnouveau/client/patchouli/GlyphPressProcessor.java) (and the others) are encountering the same issue I had.

**Comment by baileyholl** [comment]
Do you have Apotheosis and Farmers Delight in the same pack?

**Comment by baileyholl** [comment]
There is a known issue with Apotheosis and Farmers Delight together causing recipes to break. This is likely the cause, and there is nothing I can do at this point until Apotheosis releases a fix.

**Comment by BluSodah** [comment]
I only have farmers delight and my friend got this error. So, it cant be a apotheosis. The reddit has a comment farther down the page saying its patchouli's fault because its marking valid recipes as invalid.
