### ISSUE TITLE
TileEntity type 

### ISSUE THREAD

**Issue by Sam-Wave** [baileyholl/Ars-Nouveau#226]
**[13:56:26 ERROR]: A TileEntity type com.hollingsworth.arsnouveau.common.block.tile.PortalTile has thrown an exception trying to write state. It will not persist, Report this to the mod author**
java.lang.NullPointerException: null
at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?] {re:classloading}
at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
at com.hollingsworth.arsnouveau.common.block.tile.PortalTile.func_189515_b(PortalTile.java:55) ~[?:1.15.1] {re:classloading}
at net.minecraft.world.chunk.Chunk.func_223134_j(Chunk.java:461) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:290) ~[?:?] {re:classloading}
at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:710) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ChunkManager.func_222965_e(ChunkManager.java:377) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111] {}
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_111] {}
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_111] {}
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_111] {}
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111] {}
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111] {}
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_111] {}
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_111] {}
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111] {}
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111] {}
at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:335) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:811) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:600) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:951) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:765) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:277) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111] {}

**Comment by Sam-Wave** [comment]
Hi, This error is spawning on the console of my server, tks.

**Comment by baileyholl** [comment]
I cannot reproduce this without more context, but I see this was long ago. If you encounter this again, please post the full crash log as a file or gist.
