### ISSUE TITLE
Ritual of Overgrowth crashing Server

### ISSUE THREAD

**Issue by Yerova** [baileyholl/Ars-Nouveau#234]
The server is crashing, while I use the Ritual of Overgrowth

I dont know much... but here is the log:

[log.txt](https://github.com/baileyholl/Ars-Nouveau/files/6478704/log.txt)

Lg Yerova

**Comment by EndlessVoid1** [comment]
"[14May2021 11:39:49.415] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 2d1818f5-860c-44bc-bc83-c46a54b19972
[14May2021 11:39:49.426] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: **Encountered an unexpected exception**"

"net.minecraft.**crash.ReportedException: Ticking block entity"**

"**Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/IParticleFactory**
...
..._at com.hollingsworth.arsnouveau.client.particle.ParticleUtil.spawnTouch(ParticleUtil.java:111) ~[ars_nouveau:1.16]
	at com.hollingsworth.arsnouveau.common.ritual.RitualOvergrowth.tick(RitualOvergrowth.java:63) ~[ars_nouveau:1.16]
	at com.hollingsworth.arsnouveau.api.ritual.AbstractRitual.tryTick(AbstractRitual.java:38) ~[ars_nouveau:1.16]
	at com.hollingsworth.arsnouveau.common.block.tile.RitualTile.func_73660_a(RitualTile.java:112) ~[ars_nouveau:1.16]_..."

Some stuff I found looking through the log. Don't work on this codebase so I'm no help.

Hope it helps! (Someone working on the code...)

**Comment by baileyholl** [comment]
Sorry about that, use this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3310018

You should be able to use it on servers without the clients needing to update, but I have not tested it.
