### ISSUE TITLE
The second phase of the chimera caused the game to crash

### ISSUE THREAD

**Issue by LTCatt** [baileyholl/Ars-Nouveau#324]
java.lang.NullPointerException: Ticking entity
	at com.hollingsworth.arsnouveau.api.util.BlockUtil.distanceFrom(BlockUtil.java:56) ~[?:1.21.0] {re:classloading}
	at com.hollingsworth.arsnouveau.common.entity.goal.chimera.ChimeraDiveGoal.func_75246_d(ChimeraDiveGoal.java:87) ~[?:1.21.0] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}

Crash report and logs: [report.zip](https://github.com/baileyholl/Ars-Nouveau/files/6952127/mod.zip)

Version 1.21.0, Forge 1.16.5-36.2.0

**Comment by baileyholl** [comment]
Please try version 1.21.1. https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3420925
