### ISSUE TITLE
1.18.1 Drygmy familiar server error

### ISSUE THREAD

**Issue by UnseenAcademical** [baileyholl/Ars-Nouveau#439]
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.damagesource.DamageSource.m_7639_()" because the return value of "net.minecraftforge.event.entity.living.LootingLevelEvent.getDamageSource()" is null
	at TRANSFORMER/ars_nouveau@2.0.0/com.hollingsworth.arsnouveau.common.entity.familiar.FamiliarDrygmy.onLootingEvent(FamiliarDrygmy.java:34)
	at TRANSFORMER/ars_nouveau@2.0.0/com.hollingsworth.arsnouveau.common.event.FamiliarEvents.fortuneEvent(FamiliarEvents.java:78)
	at net.minecraftforge.eventbus.ASMEventHandler_507_FamiliarEvents_fortuneEvent_LootingLevelEvent.invoke(.dynamic)

**Comment by baileyholl** [comment]
You are on an old version of the mod, update to the latest.
