### ISSUE TITLE
[1.16.5] Can't join server because of PortalTile TileEntity 

### ISSUE THREAD

**Issue by Timeken** [baileyholl/Ars-Nouveau#460]
[Server thread/ERROR] [net.minecraft.world.chunk.Chunk/]: A TileEntity type com.hollingsworth.arsnouveau.common.block.tile.PortalTile has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "p_229705_0_" is null
	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:150) ~[?:?]
	at com.hollingsworth.arsnouveau.common.block.tile.PortalTile.func_189515_b(PortalTile.java:70) ~[ars_nouveau:1.24.16]
	at net.minecraft.world.chunk.Chunk.func_223134_j(Chunk.java:489) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:291) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:693) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:341) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:346) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:937) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:593) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:651) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:626) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by baileyholl** [comment]
Can you paste the full log with this? And are you sure the mods are the same version on the server and client?

**Comment by baileyholl** [comment]
Would you be able to try this version to see if it fixes for you? May be needed on server and client.
https://maven.blamejared.com/com/hollingsworth/ars_nouveau/ars_nouveau-1.16.5/1.24.16.11/
If not, deleting the block via the command line should get you sorted until a release.

**Comment by Timeken** [comment]
I put the updated version on both the client and the server and it works fine now. I did not have to delete the block either.
