### ISSUE TITLE
[1.18] net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace

### ISSUE THREAD

**Issue by bastetfurry** [baileyholl/Ars-Nouveau#484]
Might be solvable by just a simple string edit, this floods my clients logs:

```
net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/ars_nouveau:apprentice_layer_1.png
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at TRANSFORMER/wildfire_gender@2.8.1/com.wildfire.render.GenderLayer.getArmorTexture(GenderLayer.java:64)
	at TRANSFORMER/wildfire_gender@2.8.1/com.wildfire.render.GenderLayer.render(GenderLayer.java:207)
	at TRANSFORMER/wildfire_gender@2.8.1/com.wildfire.render.GenderLayer.m_6494_(GenderLayer.java:33)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:131)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:62)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:43)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:129)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_98881_(InventoryScreen.java:152)
	at TRANSFORMER/minecraft@1.18.1/com.mojang.blaze3d.systems.RenderSystem.m_69890_(RenderSystem.java:1149)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_98850_(InventoryScreen.java:152)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_7286_(InventoryScreen.java:110)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:93)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6305_(EffectRenderingInventoryScreen.java:30)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_6305_(InventoryScreen.java:90)
	at TRANSFORMER/forge@39.0.79/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:395)
	at TRANSFORMER/forge@39.0.79/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:388)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:886)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.79/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

**Comment by bastetfurry** [comment]
Yes, thanks, then i have the real culprit, Wildfire Female Gender Mod.
Sadly no way to blacklist your mod in that mod for not trying to modify the armor so i will remove Wildfires from our private pack as we want to keep your magic pack. :)
