### ISSUE TITLE
1.19 Crash Exception generating new chunk

### ISSUE THREAD

**Issue by MichaelChickson** [baileyholl/Ars-Nouveau#592]
Crash on generating new world:

Time: 7/2/22, 11:37 PM
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:deep_dark]=net.minecraft.world.level.biome.Biome@12952df9}, Reference{ResourceKey[minecraft:worldgen/biome / ars_nouveau:archwood_forest]=net.minecraft.world.level.biome.Biome@65853853}, Reference{ResourceKey[minecraft:worldgen/biome / byg:coconino_meadow]=net.minecraft.world.level.biome.Biome@44ce89ea}]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.chunk.ChunkGenerator.md306387$lambda$updateFeaturesPerStep$1$0(ChunkGenerator.java:852) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinChunkGenerator,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23113!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:395) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinChunkGenerator,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:619) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23118!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:617) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.chunk.ChunkGenerator.md306387$lambda$updateFeaturesPerStep$1$0(ChunkGenerator.java:852) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinChunkGenerator,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23113!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:395) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinChunkGenerator,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:619) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23118!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:617) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: -1,-1
	Position hash: -1
	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@3d891573
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:619) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23118!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:617) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Level name: You're a creeper Harry
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:348) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:301) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:626) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4486526184 bytes (4278 MiB) / 8690597888 bytes (8288 MiB) up to 15770583040 bytes (15040 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 64394.71
	Virtual memory used (MB): 43986.61
	Swap memory total (MB): 31744.00
	Swap memory used (MB): 1943.14
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15040m -Xms256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:clienttweaks (incompatible), mod:secondchanceforge, mod:supermartijn642configlib (incompatible), mod:coralreef (incompatible), mod:jei (incompatible), mod:attributefix (incompatible), mod:libraryferret, mod:goblintraders (incompatible), mod:dynamiclights (incompatible), mod:strawgolem (incompatible), mod:reap (incompatible), mod:kleeslabs (incompatible), mod:waystones (incompatible), mod:forgeendertech, mod:adfinders, mod:clumps (incompatible), mod:journeymap (incompatible), mod:controlling (incompatible), mod:comforts (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:naturescompass (incompatible), mod:sereneseasons (incompatible), mod:configured (incompatible), mod:alcocraft, mod:bno, mod:upgradednetherite_items (incompatible), mod:bookshelf (incompatible), mod:guardvillagers (incompatible), mod:jeed (incompatible), mod:explorerscompass (incompatible), mod:additionalstructures, mod:balm (incompatible), mod:terralith (incompatible), mod:miningmaster, mod:cloth_config (incompatible), mod:sound_physics_remastered (incompatible), mod:forge, mod:dummmmmmy (incompatible), mod:revampedwolf (incompatible), mod:upgradednetherite (incompatible), mod:advancementplaques (incompatible), mod:cleancut (incompatible), mod:torchmaster (incompatible), mod:repurposed_structures, mod:morevillagers, mod:enchdesc (incompatible), mod:burlapsack (incompatible), mod:terrablender (incompatible), mod:physicsmod (incompatible), mod:moonlight (incompatible), mod:supplementaries (incompatible), mod:mousetweaks, mod:toolbelt, mod:netherportalspread, mod:jade (incompatible), mod:spectrelib (incompatible), mod:supermartijn642corelib (incompatible), mod:darkerdepths (incompatible), mod:golems (incompatible), mod:iceberg (incompatible), mod:curios (incompatible), mod:patchouli (incompatible), mod:legendarytooltips (incompatible), mod:gravestone (incompatible), mod:collective, mod:oreexcavation (incompatible), mod:angelring (incompatible), mod:backpacked (incompatible), mod:inventoryhud, mod:runelic (incompatible), mod:upgradedcore (incompatible), mod:hunterillager, mod:wormhole (incompatible), mod:sapience, mod:architectury (incompatible), mod:animal_feeding_trough (incompatible), mod:appleskin, mod:lootr (incompatible), mod:upgradednetherite_ultimate (incompatible), mod:productivebees, mod:enhancedcelestials (incompatible), mod:byg (incompatible), mod:aquaculture, mod:fallingtree, mod:enchantwithmob (incompatible), mod:smallernetherportals, mod:chickensshed, mod:exoticbirds, mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:geckolib3 (incompatible), mod:ars_nouveau (incompatible), mod:nebs, mod:darkpaintings (incompatible), mod:betteradvancements (incompatible), Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-41.0.62
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null

**Comment by aAndrew3030** [comment]
Version 3.0.5 is still crashing with this issue for me when entering new chunks

**Comment by baileyholl** [comment]
Fixed in this version: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3860822
