### ISSUE TITLE
1.19 crash on invalid spellcast attempt

### ISSUE THREAD

**Issue by InspectorCaracal** [baileyholl/Ars-Nouveau#659]
Trying to use a spellbook when there are no spells in it, or when there's not enough mana to cast the spell, causes a full game crash with the message `java.lang.NoSuchMethodError: 'void net.minecraft.network.chat.MessageSignature.<init>(byte[])'`

I'm running the most recent version of the mod `1.19.1-3.2.7` and the current recommended Forge version `1.19 - 41.1.0`

Full trace:
```
java.lang.NoSuchMethodError: 'void net.minecraft.network.chat.MessageSignature.<init>(byte[])'
	at com.hollingsworth.arsnouveau.common.network.PacketNoSpamChatMessage.<clinit>(PacketNoSpamChatMessage.java:26) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.util.PortUtil.sendMessageNoSpam(PortUtil.java:18) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.enoughMana(SpellResolver.java:75) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.canCast(SpellResolver.java:57) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.onCastOnBlock(SpellResolver.java:117) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.ISpellCaster.castSpell(ISpellCaster.java:148) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.ISpellCaster.castSpell(ISpellCaster.java:159) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.items.SpellBook.m_7203_(SpellBook.java:83) ~[ars_nouveau-1.19.1-3.2.7.jar%23144!/:3.2.7] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1053) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:158) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

**Comment by Alexthw46** [comment]
You are using the Minecraft 1.19.0 for a mod that only works for 1.19.1+. Due to chat changes (used to send you error messages) Ars is not backward compatible, even if many other mods will work on both. So try to just change the forge version to 42.x.x and hope it works, or rollback to version 3.1.0, the last working on 1.19.0

**Comment by InspectorCaracal** [comment]
Oh! Well that's an easy fix, thank you.
