### ISSUE TITLE
NullPointerException crashes the server in 1.18.2

### ISSUE THREAD

**Issue by JoseArquesGomez** [baileyholl/Ars-Nouveau#707]
Crash report with NullPointerException:

> ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/19/22, 1:40 AM
Description: Saving entity NBT

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "p_129298_" is null
	at net.minecraft.nbt.StringTag.m_129297_(StringTag.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,re:classloading,pl:mixin:APP:rhino-common.mixins.json:StringTagMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundTag.m_128359_(CompoundTagMixin.java:200) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:nbt.CompoundTagMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.NbtCompoundMixin,pl:mixin:A}
	at com.hollingsworth.arsnouveau.common.entity.familiar.FamiliarEntity.m_7380_(FamiliarEntity.java:232) ~[ars_nouveau-1.18.2-2.7.8.jar%2393!/:2.7.8] {re:classloading}
	at net.minecraft.world.entity.Entity.m_20240_(EntityMixin.java:1494) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorEntity,pl:mixin:APP:botania_xplat.mixins.json:MixinEntity,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:identity.mixins.json:EntityMixin,pl:mixin:APP:identity.mixins.json:accessor.EntityAccessor,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:EntityMixin_Optimize,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.EntityMixin_ActivationRange,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at draylar.identity.api.PlayerIdentity.sync(PlayerIdentity.java:55) ~[identity-2.3.0-1.18.2-forge.jar%23205!/:?] {re:mixin,re:classloading}
	at draylar.identity.api.PlayerIdentity.sync(PlayerIdentity.java:45) ~[identity-2.3.0-1.18.2-forge.jar%23205!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.handler$bfe000$tickIdentity(PlayerMixin.java:9640) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:botania_xplat.mixins.json:MixinPlayer,pl:mixin:APP:pehkui.mixins.json:EntityVehicleHeightOffsetMixin,pl:mixin:APP:pehkui.mixins.json:PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat115plus.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:identity.compat.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:reach.PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:identity.mixins.json:PlayerEntityAttackMixin,pl:mixin:APP:identity.mixins.json:PlayerEntityMixin,pl:mixin:APP:identity.mixins.json:player.PlayerEntityDataMixin,pl:mixin:APP:identity.mixins.json:player.PlayerEntityTickMixin,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:botania_xplat.mixins.json:MixinPlayer,pl:mixin:APP:pehkui.mixins.json:EntityVehicleHeightOffsetMixin,pl:mixin:APP:pehkui.mixins.json:PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat115plus.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:identity.compat.PlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:reach.PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:identity.mixins.json:PlayerEntityAttackMixin,pl:mixin:APP:identity.mixins.json:PlayerEntityMixin,pl:mixin:APP:identity.mixins.json:player.PlayerEntityDataMixin,pl:mixin:APP:identity.mixins.json:player.PlayerEntityTickMixin,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerPlayer,pl:mixin:APP:pehkui.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:identity.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:identity.mixins.json:player.RespawnDataCopyMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.players.PlayerList.handler$bnl000$arclight$playerQuitPre(PlayerListMixin.java:1081) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:pehkui.mixins.json:PlayerManagerMixin,pl:mixin:APP:byg.mixins.json:common.MixinPlayerList,pl:mixin:APP:identity.mixins.json:PlayerManagerMixin,pl:mixin:APP:identity.mixins.json:player.PlayerManagerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinPlayerList,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin,pl:mixin:APP:securitycraft.mixins.json:camera.PlayerListMixin,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11286_(PlayerListMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:pehkui.mixins.json:PlayerManagerMixin,pl:mixin:APP:byg.mixins.json:common.MixinPlayerList,pl:mixin:APP:identity.mixins.json:PlayerManagerMixin,pl:mixin:APP:identity.mixins.json:player.PlayerManagerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinPlayerList,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin,pl:mixin:APP:securitycraft.mixins.json:camera.PlayerListMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerPlayNetHandlerMixin.java:1063) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:pehkui.mixins.json:reach.compat118minus.ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:reach.ServerPlayNetworkHandlerMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:mixins.artifacts.json:item.umbrella.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129541_(ConnectionMixin.java:394) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ConnectionMixin_Optimize,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:158) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin}

**Comment by JoseArquesGomez** [comment]
I just found it was Identity problem.

Sorry for creating this issue xD
