### ISSUE TITLE
Invalid spell cast found! This is a bug and should be reported!

### ISSUE THREAD

**Issue by Anaerin** [baileyholl/Ars-Nouveau#710]
As requested by the message in the server log:
```
[19Sep2022 16:02:54.847] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:49]: =======
[19Sep2022 16:02:54.847] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:50]: Invalid spell cast found! This is a bug and should be reported!
[19Sep2022 16:02:54.847] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:51]: Projectile -> Conjure Terrain -> AOE x2
[19Sep2022 16:02:54.847] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:52]: Casting player:
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:53]: ServerPlayerEntity['ademoes7'/3539403, l='ServerLevel[world]', x=2140.84, y=50.95, z=-1127.33]
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:54]: Casting tile:
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:55]: null
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:56]: =======
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at java.util.ArrayList.get(ArrayList.java:435)
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at com.hollingsworth.arsnouveau.api.spell.SpellContext.nextSpell(SpellContext.java:47)
[19Sep2022 16:02:54.848] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at com.hollingsworth.arsnouveau.api.spell.SpellResolver.resolveEffects(SpellResolver.java:142)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at com.hollingsworth.arsnouveau.api.spell.SpellResolver.onResolveEffect(SpellResolver.java:128)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at com.hollingsworth.arsnouveau.common.entity.EntityProjectileSpell.func_70227_a(EntityProjectileSpell.java:236)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at com.hollingsworth.arsnouveau.common.entity.EntityProjectileSpell.func_70071_h_(EntityProjectileSpell.java:103)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.world.World.func_217390_a(World.java:554)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
[19Sep2022 16:02:54.849] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[19Sep2022 16:02:54.850] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[19Sep2022 16:02:54.850] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[19Sep2022 16:02:54.850] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[19Sep2022 16:02:54.850] [Server thread/INFO] [STDERR/]: [com.hollingsworth.arsnouveau.api.spell.SpellContext:nextSpell:57]:    at java.lang.Thread.run(Thread.java:750)
```

MC Version: 1.16.5
Forge Version: 1.16.5-36.2.39
Ars Version: 1.16.5-1.25.7

**Comment by Alexthw46** [comment]
Uhm, not sure why it have been reported only now since it's a months old feature, but that's from an addon and not base ars. Should be able to fix that pretty soon.
