### ISSUE TITLE
[Crash] 1.19.2, Forge 43.1.33 crash at startup

### ISSUE THREAD

**Issue by Daltaxy** [baileyholl/Ars-Nouveau#720]
Version Info

Minecraft, 1.19.2
Ars Nouveau, latest
Forge 43.1.33
Steps to Reproduce
start the game
Crash report (~/logs/latest.log) 
net.minecraftforge.fml.ModLoadingException: Ars Nouveau (ars_nouveau) encountered an error during the common_setup event phase
§7java.lang.NullPointerException: null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.19.2-43.1.33.jar%23491!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:306) ~[fmlcore-1.19.2-43.1.33.jar%23490!/:?] {}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.2-43.1.33.jar%23490!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:306) ~[fmlcore-1.19.2-43.1.33.jar%23490!/:?] {}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:551) ~[client-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:APP:fastload.mixins.json:MinecraftClientMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:globaldataandresourcepacks.mixins.json:ClientPackFinderMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.33.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderers.m_173590_(BlockEntityRenderers.java:17) ~[client-1.19.2-20220805.130853-srg.jar%23489!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers.registerBlockEntityRenderer(EntityRenderersEvent.java:129) ~[forge-1.19.2-43.1.33-universal.jar%23494!/:?] {re:classloading,pl:eventbus:A}
	at com.hollingsworth.arsnouveau.client.events.ClientHandler.registerRenderers(ClientHandler.java:69) ~[ars_nouveau-1.19.2-3.4.0.jar%23174!/:3.4.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.hollingsworth.arsnouveau.client.events.__ClientHandler_registerRenderers_RegisterRenderers.invoke(.dynamic) ~[ars_nouveau-1.19.2-3.4.0.jar%23174!/:3.4.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.33.jar%23491!/:?] {}
	... 20 more

latest.log : https://gist.github.com/Daltaxy/6600108a1f048472c7cf63e10ba5ebed
This is undoubtedly due to the forge update's breaking changes...

**Comment by baileyholl** [comment]
Hello, I believe your issue is with betterfurnacesreforged.

java.lang.NoClassDefFoundError: harmonised/pmmo/api/events/FurnaceBurnEvent
	at TRANSFORMER/betterfurnacesreforged@1.19.2-1.0.2/wily.betterfurnaces.init.Registration.lambda$static$4(Registration.java:72)
