### ISSUE TITLE
Ars Nouveau has failed to load correctly

### ISSUE THREAD

**Issue by DilerFlora** [baileyholl/Ars-Nouveau#898]
Well I tried changing the versions but It will always fail. Im not sure what to do

	Mod File: /C:/Users/xxx/AppData/Roaming/.minecraft/mods/ars_nouveau-1.19.2-3.12.0.jar
	Failure message: Ars Nouveau (ars_nouveau) has failed to load correctly
		java.lang.NoSuchMethodError: 'int net.minecraft.world.item.CreativeModeTab.getGroupCountSafe()'
	Mod Version: 3.12.0
	Mod Issue URL: https://github.com/baileyholl/Ars-Nouveau
	Exception message: java.lang.NoSuchMethodError: 'int net.minecraft.world.item.CreativeModeTab.getGroupCountSafe()'
	
Stacktrace:
	at com.hollingsworth.arsnouveau.ArsNouveau.<clinit>(ArsNouveau.java:56) ~[ars_nouveau-1.19.2-3.12.0.jar%23157!/:3.12.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.0.jar%23166!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.0.jar%23165!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

I can send more, If thats important- Really not sure what to send actually

**Comment by Alexthw46** [comment]
You can't use Ars on 1.19.3+. Either drop Ars or play in 1.19.2 or lower
