### ISSUE TITLE
[Bug] [1.19.2] missing getName() method of ArmorMaterial on the server side

### ISSUE THREAD

**Issue by Tidy-Bear** [baileyholl/Ars-Nouveau#945]
https://github.com/baileyholl/Ars-Nouveau/blob/3bea1cab46f7f8718a12220b5b831b6f67ac6c5b/src/main/java/com/hollingsworth/arsnouveau/common/armor/Materials.java#L76-L80

In vanilla, usages of the method only appear on the client side, but it's not annotated with `@OnlyIn(Dist.CLIENT)` and other mods may call it on the server side, causing compatibility error like below. 

```
[2023-04-24 00:34:10.055] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /101.88.65.33:57435
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.hollingsworth.arsnouveau.common.armor.Materials$ModdedArmorMaterial does not define or inherit an implementation of the resolved method 'abstract java.lang.String m_6082_()' of interface net.minecraft.world.item.ArmorMaterial.
	at defeatedcrow.hac.core.climate.register.ArmorMaterialRegister.lambda$getHeatPreventAmount$0(ArmorMaterialRegister.java:59) ~[_HeatAndClimate-1.19.2-4.alpha5-forge.jar%23232!/:1.19.2_v4-alpha5]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652) ~[?:?]
	at defeatedcrow.hac.core.climate.register.ArmorMaterialRegister.getHeatPreventAmount(ArmorMaterialRegister.java:59) ~[_HeatAndClimate-1.19.2-4.alpha5-forge.jar%23232!/:1.19.2_v4-alpha5]
	at defeatedcrow.hac.core.util.DCItemUtil.getItemResistantData(DCItemUtil.java:213) ~[_HeatAndClimate-1.19.2-4.alpha5-forge.jar%23232!/:1.19.2_v4-alpha5]
	at defeatedcrow.hac.core.event.LivingTickEventDC.onLivingClimateUpdate(LivingTickEventDC.java:172) ~[_HeatAndClimate-1.19.2-4.alpha5-forge.jar%23232!/:1.19.2_v4-alpha5]
	at defeatedcrow.hac.core.event.LivingTickEventDC.onLivingTick(LivingTickEventDC.java:51) ~[_HeatAndClimate-1.19.2-4.alpha5-forge.jar%23232!/:1.19.2_v4-alpha5]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.0-universal.jar%23289!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23284!/:?]
	... 9 more
```

[Here](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.19.X_main/src/main/java/defeatedcrow/hac/core/climate/register/ArmorMaterialRegister.java) are related codes from `Heat and Climate` if needed.

**Comment by baileyholl** [comment]
Huh, good catch.
